### ISSUE TITLE
Add `aria-current` to breadcrumb and pagination widgets

### ISSUE THREAD

**Issue by MichielBijl** [cehfisher/a11y-style-guide#143]
Hi 👋🏼

For both the [breadcrumb](http://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-breadcrumbs) and [pagination](http://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination) widget you can add `aria-current="page"` to the link that points to, well, the current page. This will tell AT that the focused link (when it has `aria-current`) points to the current page.

You can apply this to all navigation types that have a “current” state.

Related links:

- [Breadcrumbs in the ARIA Authoring Practices](http://w3c.github.io/aria-practices/#breadcrumb)
- [aria-current in the ARIA spec](http://w3c.github.io/aria/aria/aria.html#aria-current)
- [Using aria-current by Léonie Watson](http://tink.uk/using-the-aria-current-attribute/)

**Comment by cehfisher** [comment]
thanks for the ticket and PR guys! I made some changes and updated the demo site. please review and get back to me on any additional changes that may be needed. thanks!
