### ISSUE TITLE
Skip nav component 

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#153]
we are using a `skip to content` button on this site, but need to do a quick write-up of the pieces some one else might need to replicate this.

**Comment by dengeist** [comment]
Maybe you could refer readers to some of the common patterns for accessible hiding? [H5BP's .visuallyhidden](https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/main.css#L135-L147) and [its :focus derivative](https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/main.css#L155-L166) make accomplishing this very easy. I could make an addition if you want! :)

**Comment by cehfisher** [comment]
that would be a good addition to this component @dengeist! PRs always welcome :)

**Comment by scottaohara** [comment]
i may have written all about how to [appropriately hide content](http://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html)  :)

feel free to reference
