### ISSUE TITLE
Link focus component

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#154]
add `button` to link focus example. point out bug @dengeist mentioned on Twitter https://codepen.io/dengeist/pen/LyomBb?editors=1100

**Comment by dengeist** [comment]
Just realized I totally left out other focusable controls. Inputs, etc--doesnt this bug affect all of them?

**Comment by cehfisher** [comment]
yes, i assume it would affect all control elements using the base focus styling/functionality. something to google, test, and update. if you find out anything, let me know!
