### ISSUE TITLE
Font size examples

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#160]
Using rem vs pt vs vw examples of what is best for browser resizing (ex. https://madebymike.com.au/writing/fluid-type-calc-examples)

**Comment by kendrick** [comment]
Are you interested in adding guidance about why not to size type in pixels, or in adding a responsive/fluid typography pattern instead? (Or both?)

**Comment by cehfisher** [comment]
Probably both, but I'll take whatever you have time for and can expand as needed at a later point. :)

**Comment by kendrick** [comment]
Cool, I can write a short explainer on using relative units and possibly add a fluid typography pattern in the future.

**Comment by cehfisher** [comment]
@kendrick is there anything i can do to help you on this component?

**Comment by kendrick** [comment]
I have some notes cobbled together that I'll be able to use to craft some guidance later this week.

**Comment by cehfisher** [comment]
nice! feel free to push up what you have too and we can help you cross the finish line. it takes a community :)
