### ISSUE TITLE
Read more link examples - movie quote attributions are hidden from some users.

### ISSUE THREAD

**Issue by fuzzbomb** [cehfisher/a11y-style-guide#165]
In the Read More link examples, the movie quote attributions are visually-hidden.  Screen readers announce them, 

These attributions are probably of interest to everyone, and hiding them from some users is a bad pattern to encourage in the style guide.  It's unrelated to the main purpose of the read-more-links section of the guide.

http://a11y-style-guide.com/style-guide/section-general.html#kssref-general-read-more

e.g. The `aria-describedby` example has "This is a quote from the 1948 movie The Treasure of the Sierra Madre." wrapped in a `p.visually-hidden` element.

Suggestion: display the attributions visually.  Blockquote tags would serve well here.

**Comment by cehfisher** [comment]
> the movie quote attributions are visually-hidden. Screen readers announce them
this is kind of the point. The 'read more' section is showing different ways to add additional content for people using screenreaders. This is an exaggerated example, so might need clarification as such. thanks for the feedback!

**Comment by fuzzbomb** [comment]
Let me have another go at explaining it.  My point is the invisible movie quote sources (in examples 3 and 4) are unrelated to the WCAG Link Purpose AAA techniques being demonstrated.  I can't see any reason why a screen reader user deserves these but a sighted user doesn't.

I think the bullet points in the introduction to the Read More Links section are out of step with the demos which follow.

The section introduction says example 3 is about using "the class `visuallyhidden` to visually hide more information about the link", but example 3 actually demonstrates uses of `aria-describedby` to enhance the link text.    None of the bullet points in the introduction mention an `aria-describedby` example, so that's why I say the introduction is out of step with the demos.  The invisible Sierra Madre source doesn't form part of the link text, and for all we know the linked document might not mention it at all.

Example 4 is the real demo of the `visuallyhidden` class - where invisible text is contained _inside_ the link.  But there's also an invisible quote source for Ghostbusters outside the link, which isn't needed to demonstrate the link text technique.  

The introduction says example 4 is about turning "read more links into buttons, when you can, since they allow for more labeling options".  But the read-more link in example 4 doesn't actually look like a button - it has the same little red triangle as the previous examples.
