### ISSUE TITLE
Pagination Arrow Updates

### ISSUE THREAD

**Issue by scottaohara** [cehfisher/a11y-style-guide#168]
Per mention in [this commit](https://github.com/cehfisher/a11y-style-guide/commit/4213d0cf393fb7e9397eef305d98a6e21593e583), the arrows are being read aloud by VO.

likely want to revise these to be SVGs that we can set to aria-hidden, so they will not be read aloud, or update to CSS generated triangles or background images?

**Comment by Martskin** [comment]
@scottaohara While this issue is titled "BreadCrumb Arrow Updates" I think it's meant to be "Pagination Arrow Updates". 

As I was looking into it I noticed some other issues with Pagination. I opened a PR here with some refactoring/additions suggestions: https://github.com/cehfisher/a11y-style-guide/pull/175

**Comment by scottaohara** [comment]
Thanks @Martskin 

updated the title of the issue, and will give your PR a look over soon.  Appreciate the help!

**Comment by cehfisher** [comment]
this looks great @Martskin! I did some quick tests with VO and heard it read "dimmed" on the inactive pager elements...which seems like a legit response according to some research (https://stackoverflow.com/questions/29283878/voiceover-announces-dimmed-instead-of-disabled-for-buttons).

@scottaohara how does this page look to you now? http://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination

**Comment by cehfisher** [comment]
oh should have mentioned, please close the ticket if resolved @scottaohara. thanks!

**Comment by Martskin** [comment]
Thanks @cehfisher ! 
Interesting, from that link it looks like it's the `pointer-events: none;` and not `aria-disabled="true"` that causes it to read as "Dimmed".

**Comment by cehfisher** [comment]
yeah this is a first for me too, so wanted to run it by Scott who does more a11y audits than I. might be a normal OK thing

**Comment by scottaohara** [comment]
Just gave this a look, and it's much better.
Is there a certain AT + browser combo where the link is announced as 'dimmed' when the aria-disabled is removed?  I wasn't getting that w/VoiceOver, even with `pointer-events: none` set.  

The visual styling is definitely tied to the `.pagination__link--is-disabled`, but now that these utilize the `[aria-disabled="true"]` should the disabled styling be moved over to that as the selector instead of the BEM class?

**Comment by Martskin** [comment]
@scottaohara Good point. I see that that's a pattern used in places in the project.
https://github.com/cehfisher/a11y-style-guide/blob/39ca46d9c89431aabcae50d7eec95661667ec9f0/docs/css/toggles.css#L1

Which reminds me, as I was working on this issue I was going to suggest possibly adding a "Code Standards" section to the guide for contributors.

**Comment by cehfisher** [comment]
@Martskin that's a great idea on the "code standards" section. what would you like to see in a document like that? have any good examples you could point us to?

@scottaohara is 

> disabled styling be moved over to that as the selector instead of the BEM class

 the only change we need here still?

**Comment by Martskin** [comment]
@cehfisher Here's one that I created for USAC:

https://indigo.universalservice.org/latest/about-indigo/code-standards.html

And here's Airbnb's:

https://github.com/airbnb/css#css
