### ISSUE TITLE
Build accessible accordion pattern

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#177]
Need to build an accordion pattern that is also accessible. Might want to borrow some ideas from @scottaohara's base accessible accordions https://github.com/scottaohara/accessible_accordions

**Comment by omguhh** [comment]
I will try this :)

**Comment by cehfisher** [comment]
sweet! I have a long list of components to add, but never enough time to do it all. ping the ticket if you need any direction or reviews :)

**Comment by cehfisher** [comment]
@omguhh how is the progress on this?

**Comment by omguhh** [comment]
Hey @cehfisher, it's going OK, I've made a skeleton of the accordion and the styling. It's taken me awhile to get used to the style guide, but it should be done soon 🎉

**Comment by cehfisher** [comment]
nice @omguhh! let @scottaohara or I know if you need any 👀  on it. also feel free to push up anything you started and we can help you finish too. we appreciate any and all effort :)

**Comment by omguhh** [comment]
Thanks @cehfisher! :) 
I've [pushed](https://github.com/cehfisher/a11y-style-guide/compare/master...omguhh:feature/accordion) a basic accordion, I've based it roughly on the the spec for it [here](https://www.w3.org/TR/wai-aria-practices/#accordion) and @scottaohara's 😅 
Can you let me know if I'm missing anything? :D

I'll work on adding it to the live demo pages.

**Comment by cehfisher** [comment]
sweet! thanks for your hard work on this @omguhh! I'll do some review this morning. don't worry about the demo part of the PR. I can flip that over for you after the review. stay tuned...

**Comment by cehfisher** [comment]
nice work @omguhh!!! I made some minor changes to the style and markup on PR #185. You can see the changes on the live demo site now - http://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-accordion

**Comment by cehfisher** [comment]
Leaving this ticket open for now to add accessibility notes to the component.

**Comment by omguhh** [comment]
It looks great @cehfisher :) 
Thanks for reviewing and merging guys! @cehfisher @scottaohara :D
