### ISSUE TITLE
Sidebar collapse button does not have hover states

### ISSUE THREAD

**Issue by alefort** [cehfisher/a11y-style-guide#186]
When hovering via mouse, over the collapse button, there's no visual indication that the element can be interacted with.

![image](https://user-images.githubusercontent.com/3220930/33443034-8c2fdeaa-d5c4-11e7-94a4-11b652476a2e.png)

**Comment by cehfisher** [comment]
Hmm in my testing I do have a hover state for this. What browser/OS combo are you using @alefort?
![a11y_style_guide](https://user-images.githubusercontent.com/15240149/33458908-a8aa3f02-d5ed-11e7-9cac-2e3cc2ba40f0.png)

**Comment by alefort** [comment]
That is a focus state in your screenshot. I'm pointing out the lack of a
hover state via a mouse.

**Comment by cehfisher** [comment]
ah...pays to *read* more slowly. i will be making some updates today, so will add that one in. probably should do the same treatment to the "back to top" icon as well. thanks!

**Comment by cehfisher** [comment]
@alefort I added a cursor hand on hover for this toggle button. I did mock-up something that "bounced" on hover with keyframes, but I was afraid that would be too confusing to users. closing this ticket now. reopen if you don't think that a pointer is helpful enough.

**Comment by alefort** [comment]
I'd love to see it on the demo site when it's ready.

If you only added the mouse pointer, I feel that isn't enough, there's more we can do. What about giving it a proper hover state, something in which the color, shape or size change? This would guarantee that a larger portion of the population can detect the interactivity of the element.

Material design (https://material.io/guidelines/components/buttons.html#buttons-flat-buttons) has a wonderful example of the various states of a button, and I think any button on a website should have these states defined: 

![image](https://user-images.githubusercontent.com/3220930/33515381-74383e7e-d730-11e7-945f-af01a59cd099.png)

**Comment by cehfisher** [comment]
I added a drop-shadow to the sidebar button, but I love your idea of extending the button section with states. I'll make a new ticket for that though. thanks!
