### ISSUE TITLE
Update button states

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#191]
Add button states to button section http://a11y-style-guide.com/style-guide/section-general.html#kssref-general-buttons

**Comment by stuartjnelson** [comment]
HI @cehfisher sorry could I have some more info? Do you mean some info about button states? Apologies if I am missing something simple.

**Comment by cehfisher** [comment]
Yes sorry @stuartjnelson, meant to add more details to this ticket. Thinking something like this that shows all the various button states: hover, disabled, etc.
![states](https://user-images.githubusercontent.com/15240149/34844504-574dd8b6-f6d7-11e7-8eae-f59bb40585e8.png)

**Comment by stuartjnelson** [comment]
No worries @cehfisher. Something like this [codepen](https://codepen.io/stuartjnelson/pen/MrqwKZ). 

1. Are you happy with the buttons state being the button text or would you like a separate label like in the screenshot example
2. Would you like the buttons to also be interactive (eg, the normal button if focus on will show the focused style)
3. Would you like these buttons to go below the current 4 example buttons or replace them?

**Comment by cehfisher** [comment]
yes that looks like the correct way forward @stuartjnelson.

1. No need for a separate label. Button text should be god enough. Or you could break it down into sections like this: http://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination

2. No I think the buttons do no have to be interactive, if they are showing states. However, the base buttons would essentially inherit these states, so they would be interactive. If that makes sense.

3. Put the states below the current buttons. You can just add markup and styling to the current button component. Much like the pagination component: https://github.com/cehfisher/a11y-style-guide/blob/master/src/components/pagination/pagination.twig
https://github.com/cehfisher/a11y-style-guide/blob/master/src/components/pagination/pagination.scss

**Comment by cehfisher** [comment]
Any progress on this @stuartjnelson? I can just take it from here if you prefer. Another example layout: https://designsystem.digital.gov/components/buttons/
