### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by scottaohara** [cehfisher/a11y-style-guide#192]
Per the contributing guidelines you've created a placeholder for, once those are squared away might i suggest the next step would be to create a preformatted issue template?

e.g. creating a .github folder with an issue template markdown file within:
.github > issue_template.md

**Comment by cehfisher** [comment]
@scottaohara do you mean for submitting tickets? might also suggest creating a dummy pattern example. sometimes the placement of such files is half the battle (as in, don't put it in the `dist` folder or it will be erased).

**Comment by scottaohara** [comment]
It’d be for when creating new github issues. Preset issue template(s). I can show you an example next time we are both online
