### ISSUE TITLE
site is insecure, recommend implementing HTTPS

### ISSUE THREAD

**Issue by JulianNorton** [cehfisher/a11y-style-guide#225]
## Issue
The site does not use HTTPS and is being marked as insecure.

#### resources
* https://troyhunt.com/heres-why-your-static-website-needs-https/
* https://www.youtube.com/watch?time_continue=7&v=_BNIkw4Ao9w
the tl;dr is worst case scenario bad actors can insert malicious code to the site. Best case it makes people trust the site more by seeing the green lock icon.

## Example

<img width="670" alt="screenshot of a11y style guide site showing insecure warning from Google Chrome" src="https://user-images.githubusercontent.com/2412992/46743638-7facb680-cc77-11e8-87e8-8386dbcc2c68.png">

## Additional Information
https://letsencrypt.org/ could be used to get HTTPS for free. Happy to help in anyway I can. How is the site being served currently?

**Comment by cehfisher** [comment]
@JulianNorton It is a GitHub page technically, just with a nicer URL. Prob could add this certificate on to help with validity. Thanks for the idea!

**Comment by cehfisher** [comment]
Updated domain name to point to new GitHub cert. Will take up to 24 hours for the certificate to be issued. Will update the a11y SG once cert is finalized.

**Comment by cehfisher** [comment]
Finalized already. Please retest @JulianNorton, but I do see https working now. Thanks!

**Comment by JulianNorton** [comment]
Awesome! Thanks Carie.
Julian
