### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by madebyhector** [cehfisher/a11y-style-guide#227]
## Issue
Can't install. get an error running `npm install`

Specific error

npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/hector.a.rodriguez/.nvm/versions/node/v7.4.0/bin/node" "/Users/hector.a.rodriguez/.nvm/versions/node/v7.4.0/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!  /projects/a11y-style-guide/npm-debug.log

## Installation process followed
- git clone repo
- Navigate to the project root (a11y_style_guide)
- nvm install stable 
- nvm use stable
- npm install (error here)

## Additional Information
Operating System and version: 
MacOS High Sierra
npm version 4.0.5
nvm version 0.33.1

npm log has been attached

[npm-debug.log](https://github.com/cehfisher/a11y-style-guide/files/2465962/npm-debug.log)

**Comment by widescreenBob** [comment]
Hey, this is what I would try.
Delete the node modules folder.

nvm use
npm install

**Comment by cehfisher** [comment]
thanks for letting me know about this @madebyhector! I think we chatted a bit about this at A11yTO a bit. I'm just getting back from traveling/conference so give me a day or so to look and I'll update the ticket. thanks :)

**Comment by cehfisher** [comment]
@madebyhector thanks for the ticket! there were some node modules that needed some updating. please try again with the new fixes and let me know if you get stuck. thanks! Carie

**Comment by elmnt** [comment]
This solution worked for me too, thanks!
