### ISSUE TITLE
Dropdown menu on touch devices - remains open

### ISSUE THREAD

**Issue by djmtype** [cehfisher/a11y-style-guide#253]
## Issue
On touch devices, the dropdown menu remains open and the submenus revealed even when there is no focus. 

## Example
https://a11y-style-guide.com/style-guide/section-navigation.html#a11y-menu

## Additional Information
Operating System and version: iOS 12
Browser and version: Safari 12 on iPad Pro 2
Assistive technology used (if applicable):

**Comment by Malvoz** [comment]
I don't see the issue on Android 9, Chrome 73. 

@cehfisher 
As an aside, the "basic navigation" menu links take you to the top of the page on-click and that's a tad frustrating when just clicking around and testing.

**Comment by cehfisher** [comment]
@djmtype - I tested this too and did not see it on my iOS device. I will dig into it a bit.

@Malvoz - if I am remembering correctly, I added those as `#` links which makes sense why it goes back to the top of the page. I was getting validation errors when I left the links empty. maybe I could link to `#kssref-navigation-navigation-basic` so it at least stays in the section.

**Comment by Malvoz** [comment]
@cehfisher `href="#!"` allows for clickable links, but without moving focus/scrolling top, if you're okay with that. I think it's quite natural to test-click interactive elements in examples and so moving focus can be interruptive. ^^

**Comment by djmtype** [comment]
Here's [a link to better illustrate my issue](https://cloudup.com/cBoMqrq45Ho) with iOS 12.3.1 and Safari.

**Comment by cehfisher** [comment]
Thanks for the info @Malvoz and @djmtype! Just catching up with this project. I will test out the proposed solution and get back to you on implementation.

**Comment by djmtype** [comment]
I've upgraded iOS since. It works as intended on iOS 13.2 Safari.
