### ISSUE TITLE
Basic Navigation bar uses non-ideal pattern

### ISSUE THREAD

**Issue by aardrian** [cehfisher/a11y-style-guide#256]
## Issue
The pattern at this URL:
https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-navigation-basic

* Uses a `role="menu"` for basic navigation
* The third example is missing required children `menuitem` roles.

From [ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#menubar):

> The `menubar` role is used to create a menu bar similar to those found in Windows, Mac, and Gnome desktop applications. A menu bar is used to create a consistent set of frequently used commands. Authors SHOULD ensure that `menubar` interaction is similar to the typical menu bar interaction in a desktop graphical user interface.

This pattern should be reserved for web pages trying to re-create / mimic / masquerade as native OS applications. In which case, it _may_ also only be appropriate in a region with `role="application"`.

I recommend removing all the ARIA roles from these examples.

**Comment by cehfisher** [comment]
Thanks for your feedback! I will work on some updates on these.

**Comment by cehfisher** [comment]
Updated! Thanks 👍
