### ISSUE TITLE
is visually-hidden text in pagination links a problem? 

### ISSUE THREAD

**Issue by hollsk** [cehfisher/a11y-style-guide#268]
## Issue
Some of the markup on the Navigation example page contains visually-hidden text to supplement the link text in pagination controls, e.g. `<span class="visuallyhidden">page </span>2`. 

Does this matter to voice input users? I know that the A11y Style Guide is targeting WCAG 2.0 and not WCAG 2.1, and that in any case the label _is_ in the name even though some of it can't be seen. But a coworker asked me about the pattern and I don't have a good answer for them, so I thought I'd ask here 😄 

## Example

From https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination

```
<a class="pagination__link" href="#">
      <span class="visuallyhidden">page </span>2
</a>
```

**Comment by cehfisher** [comment]
That is a good question! You are correct that this library is based on WCAG 2.0 and I have not tested it with voice input devices. Could you give me more info on which technology your co-worker is using so I can test the pattern more?

**Comment by hollsk** [comment]
We're not using voice input software ourselves 🙈- just interested in whether the pattern is generally safe! 

SC 2.5.3 has a note mentioning that it's "best practice" to have the visible text of the label at the start of the accessible name, but doesn't make it a hard requirement. So the pattern as written passes WCAG, even though it doesn't use the "best practice" method. 

I was thinking that perhaps in the case of pagination it's ok because the concept of "page" is implied by the affordance of the visual design, so it wouldn't be too difficult to operate. But I don't have data or research to back that up, so I couldn't really answer my coworker's question.
