### ISSUE TITLE
The image in 'Image gallery' are not loading

### ISSUE THREAD

**Issue by jfhector** [cehfisher/a11y-style-guide#269]
Thanks for this useful style guide.

The image files in the '[Image gallery](https://a11y-style-guide.com/style-guide/section-media.html#kssref-media-image-gallery)' pattern are not loading. A placeholder 'image broken' icon is shown instead.

<img src="https://user-images.githubusercontent.com/30028540/71679485-99a44e80-2d7f-11ea-815f-85de053ed88a.png" alt="screenshot of the Image Gallery section, showing that the images are not displaying." />

**Comment by cehfisher** [comment]
Thanks for the ticket @jfhector and for the PR @kingkool68. This issue should be resolved now!
