### ISSUE TITLE
a[role="button"] needs to implement behavior

### ISSUE THREAD

**Issue by xi** [cehfisher/a11y-style-guide#27]
In the buttons section you recommend to either use a `<button>` element or to use `<a role="button">`. What is missing is that if you use the second form, you also need to implement button behavior, namely trigger a click event when pressing the spacebar. See [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role) for more information.

Note that the second form goes against the first rule of ARIA:

> If you *can* use a native HTML element or attribute with the semantics and behaviour you require **already built in**, instead of re-purposing an element and adding an ARIA role, state or property to make it accessible, **then do so**. — [Notes on Using ARIA in HTML](https://www.w3.org/TR/aria-in-html/#rule1)

In my opinion, the advice should be a bit different:

- If you need a button, use a `<button>` element
- Just because you want a link to *look* like a button, it does not need to have the role "button".
  - It is nice if your visual semantics (does it look like a button) and ARIA semantics (does it have the role "button") match up, but not too imporant.
- Remember that `<button>` defaults to `type="submit"`, so you may want to add `type="button"` in order to avoid accidentally submitting forms.
- If something navigates to a different URL, it is a link, not a button.

**Comment by cehfisher** [comment]
This is awesome feedback @xi! My goal is to give multiple options for the components (since sometimes you are limited in what markup you can modify as a developer), but I do agree that the <button> element is the best method in this case. I should have made that more obvious in the bullet points.

> What is missing is that if you use the second form, you also need to implement button behavior, namely trigger a click event when pressing the spacebar.
Thanks for letting me know about that missing piece and for the reference article. I will be updating the component later today to reflect these changes.

**Comment by xi** [comment]
I saw that you implemented some of my proposed changes in 78e02aed8df1d924b0f297c86542dbe5a0459e26. However, I fear there was one misunderstanding:

> Do not style regular links to look like buttons. If something navigates to a different URL, it is a link, not a button.

That is the opposite of what I meant: IMHO, it is ok to style a regular link to look like a button. The important aspect is that for ARIA, it is still a link.

Imagine for example a "Login" button on the frontpage. It will probably look like a call to action button, but it is definitely a link because it navigates to the login page. So it should not have `role="button"`.

**Comment by cehfisher** [comment]
Sorry for not understanding you the first time around @xi. Hoping the changes in 5f65672 resolve this issue. I appreciate your persistence :)

**Comment by xi** [comment]
It is a bit hard to find the relevant parts of that commit, but if I saw correctly you removed the note about styling links as buttons. I think the note is important because this is a very common usecase. I also saw that you still have the `<a role="button">` examples. There should definitely be a note that explains why this is not recommended. This is how I would do it:

> - It is important to know when to use a link and when to use a button. A button *does something* while a link *takes you to another URL*. Note that a link can still *look* like a button and vice versa, but that has nothing to do with ARIA.
> - A `<button>` element doesn't need anything special to work. ARIA's `role="button"` is already assigned implcitly. So if you need a button, use a true `<button>` element.
> - Remember that `<button>` defaults to `type="submit"`, so you may want to add `type="button"` in order to avoid accidentally submitting forms.
> - Your button needs a descrptive name.
>   - If it only contains an `<img>` element, make sure to set its `alt` attribute.
>   - If it only contains an icon (e.g. font awesome) use `aria-label`.
>   - Add `class="visuallyhidden"` with descriptive text to give more context to the button's purpose.

**Comment by cehfisher** [comment]
OK these buttons are tricky little things...hope to get them nailed down. Here is the commit with the latest changes (41ea59469450400569fc3049f8f0d79b6149dc95) but you can also see it on the demo site here if easier https://cehfisher.github.io/a11y-style-guide/style-guide/section-general.html#kssref-general-buttons

**Comment by xi** [comment]
Thanks for putting up with my nitpicking :)
