### ISSUE TITLE
Update instructions for contributing

### ISSUE THREAD

**Issue by coobrien** [cehfisher/a11y-style-guide#278]
Your instructions for contributing include updating of npm using the node version manager package.  Not all folks will have this installed and might get confused as to why they get an error trying to run that command.  It might be a good idea to put that as an optional step in the instructions or also put how to install nve.

**Comment by coobrien** [comment]
There also doesn't seem to be an instruction to install gulp but gulp is requited to run the app as well.

**Comment by cehfisher** [comment]
Good points @coobrien! The process has developed over time, it would be good to get a newbie's perspective. Would love some help updating these instructions, if you have some time.

**Comment by coobrien** [comment]
I can help.  Was thinking of other things too :)

**Comment by cehfisher** [comment]
@coobrien I did add a note in the contrib about making the NVM optional. I also updated some dead/old links...but could add so much more with help :)
