### ISSUE TITLE
"visuallyhidden" info in checkbox examples looks confusing

### ISSUE THREAD

**Issue by scriptype** [cehfisher/a11y-style-guide#40]
I've had a hard time to understand the purpose of these:
```html
...
<span class="visuallyhidden">The second best Led Zeppelin member is </span>Jimmy Page
...
<span class="visuallyhidden">The third best Led Zeppelin member is </span>John Paul Jones
...
<span class="visuallyhidden">The very best Led Zeppelin member is </span>Robert Plant
...
<span class="visuallyhidden">The forth best Led Zeppelin member is </span>John Bonham
```

They seem like showing content only to screen-readers to be even more helpful, at least that's what I assume after finding other `visuallyhidden` elements in other examples as well. Still, the usage in the above examples is not clear to me. Feels like we are providing poll results of some sort?

**Comment by scottaohara** [comment]
i would agree that the above visually hidden text is not necessary.

though i originally read it as kind of a joke?  since the field is asking an opinion on who the best member of led zeppelin is, and then the visually hidden text is then announcing the bias of the giver of the poll?

but yah.  maybe i'm the only one who saw that as a joke? :)

**Comment by scriptype** [comment]
Looked like a joke to me too, but it's confusing nonetheless, IMHO.

**Comment by cehfisher** [comment]
ha! it is a joke...and why not have a joke visible only to people using screen-readers? how many times do we hide content from them?

so the backstory is i'm demoing the style guide at MidCamp (https://www.midcamp.org/session/inclusive-development-using-style-guides-improve-website-accessibility) and planning to have the screen-reader read that part out-loud. again, driving home the point that all content should be accessible to all people...and how do you feel when you are left out?

**Comment by cehfisher** [comment]
but maybe i should make a note about the "hidden joke" in that component?

**Comment by scriptype** [comment]
Well, I personally wouldn't prefer having non-essential or potentially misleading things in something like a documentation. But, this is more like a personal taste, so it wouldn't be a big problem if you want them to stay.

If you imply the jokes somehow, that should clarify things more and definitely will help.

**Comment by cehfisher** [comment]
OK updated the checkboxes and radios to include a note about additional hidden content. I think it is important to point out that sometimes you *would* want to include additional info for users with screen-readers. Although this case is just for fun.

I like @scottaohara's idea of adding some additional states/styling to show other radio/checkbox options, such as disabled cursor style, or a css hover state that puts a line through the text, visually indicating the appropriate choice, but in a way that wouldn’t be accessible to screen readers. Putting that on my ever-growing to-do list. :)
