### ISSUE TITLE
duplicate ids

### ISSUE THREAD

**Issue by scottaohara** [cehfisher/a11y-style-guide#44]
```post-shortlink``` and ```copy-button``` appear multiple times across the styleguide.

it'd be best to update any JS using these hooks to instead use classes, and where necessary generate unique IDs for these elements.

**Comment by cehfisher** [comment]
I was able to make some progress on this issue, turning the `copy-button` into a class, added some ARIA labels to help make the button more descriptive, and added a success type message.

using clipboard.js (https://clipboardjs.com) as the base for this JS. might need to dig into duplicate IDs a bit.
