### ISSUE TITLE
Build footer menu component

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#64]
Creating a ticket to track progress on footer menu component.

**Comment by MichielBijl** [comment]
What’s a footer menu component?

**Comment by cehfisher** [comment]
Just another pattern showing what an accessible complex footer might look like. I'm thinking a list of links, some copyright text, some social media type links, and maybe a form field. If you have ideas, let me know or send up a PR :)

**Comment by MichielBijl** [comment]
Quick draft:

```
<footer>
  <nav aria-labelledby="footer-label">
    <h2 id="footer-label">Footer</h2>
    <h3>Services</h3>
    <ul>…</ul>
    <h3>About Planet Express</h3>
    <ul>…</ul>
    <h3>Contact</h3>
    <ul>…</ul>
  </nav>
  <nav aria-label="social">
    <ul>…</ul>
  </nav>
  <p>&copy; 3001 Planet Express Inc.</p>
</footer>
```

**Comment by cehfisher** [comment]
nice start! i'll see if I can PR something quick. just wanted to get another menu type example that was a11y friendly. people like to see all the things :)

**Comment by MichielBijl** [comment]
Cool cool cool 🙌🏽.

**Comment by cehfisher** [comment]
ok took me a bit longer to get back to this...then i made it way more complex than it probably needed to be. lol. can you take a look at the new footer nav element and let me know if i'm missing anything - http://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-navigation-footer
thanks @MichielBijl!

**Comment by MichielBijl** [comment]
I see some issues with the current implementation. Do you want a new ticket for that?

- Why are the headings at level 3?
- Why are there multiple `nav` elements?
- Why is the contact info in a `nav` element?
- `. footer__copyright ` can easily be a `p` element instead of a `div`
- Why is there a `<span class="visuallyhidden">Perform</span>` within the search’s `button` element?
- No need for the `aria-label` on the social icon links

**Comment by cehfisher** [comment]
thanks for the feedback @MichielBijl. i was away from my computer last week, but will address these changes this week now that i am back :)

**Comment by cehfisher** [comment]
OK footer nav changes have been pushed! should be good to resolve this ticket, but let me know if you see any other changes you need.
