### ISSUE TITLE
Build list component

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#73]
Creating a ticket to track progress on list component.

**Comment by MichielBijl** [comment]
Do you mean like (un)ordered lists?

**Comment by cehfisher** [comment]
Yes, unordered and ordered for sure, thinking of adding some more complex lists like accordions into this as well.

**Comment by MichielBijl** [comment]
These things:

```
<dl>
  <dt>Fruit</dt>
  <dd>Apples</dd>
  <dd>Bananas</dd>
  <dd>Pineapples</dd>
  <dt>Awesome people</dt>
  <dd>Carie</dd>
  <dd>Michiel</dd>
</dl>
```

**Comment by cehfisher** [comment]
Should be complete with this component: http://a11y-style-guide.com/style-guide/section-structure.html#kssref-structure-lists
