### ISSUE TITLE
Build table component

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#74]
Creating a ticket to track progress on table component.

**Comment by cehfisher** [comment]
Basic table component in place. Need advanced examples

**Comment by scottaohara** [comment]
this reminds me, i saw an interesting twitter thread on what to do when you are mixing component types like tables and form inputs, and how to appropriately set those up. (interesting in that no one had come to a good conclusion on what to do, so we might as well come up with something :) )

would definitely make for a good example to showcase at some point.
