### ISSUE TITLE
Document KSS node setup and workflow (CMS agnostic)

### ISSUE THREAD

**Issue by shrop** [cehfisher/a11y-style-guide#77]
The current docs at https://github.com/cehfisher/a11y-style-guide/blob/master/README.md do not seem to work outside of a Drupal theme context. Need to update to not depend on Drupal.

**Comment by cehfisher** [comment]
Updated readme a bit more after merging your PR @shrop. Should be a bit more agnostic now. Keeping this open to see if I can remove some additional .yml files or at least make then non-Drupal

**Comment by cehfisher** [comment]
Last PR should resolve this issue. Let me know if you find any other places where Drupal is mentioned.
