### ISSUE TITLE
Add good vs bad screen reader videos with examples

### ISSUE THREAD

**Issue by Robdel12** [cehfisher/a11y-style-guide#96]
First off, awesome work on this! While browsing through last night, I had an idea to add videos to each of the examples. I was thinking of demoing the different screen readers with good & bad examples to really drive home and connect the "why". 

I'm totally willing to do this! But I'm not sure where you would like the videos to be hosted or if you'd be willing to take this change :)

**Comment by cehfisher** [comment]
thanks @Robdel12! it's a work in progress...yes, please send in additional examples! send a PR over or write back into this ticket, if that is easier for you. always looking at ways to improve the tool and make it useful to others.

**Comment by cehfisher** [comment]
@Robdel12 i know this issue is closed, wanted you to see this example video http://a11y-style-guide.com/style-guide/section-media.html#kssref-media-videos

let me know what you think

**Comment by Robdel12** [comment]
That is awesome!
